// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Backend.Entities
{
    internal partial class Student
    {
        public Student()
        {
            TeamAssignments = new HashSet<TeamAssignment>();
        }

        [Key]
        public int StudentId { get; set; }
        [Required]
        public string SchoolId { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }

        [InverseProperty(nameof(TeamAssignment.Student))]
        public virtual ICollection<TeamAssignment> TeamAssignments { get; set; }
    }
}