// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Backend.Entities
{
    internal partial class TeamAssignment
    {
        [Key]
        public int StudentId { get; set; }
        [Key]
        public int ClientId { get; set; }
        [StringLength(1)]
        public string TeamNumber { get; set; }

        [ForeignKey(nameof(ClientId))]
        [InverseProperty(nameof(CapstoneClient.TeamAssignments))]
        public virtual CapstoneClient Client { get; set; }
        [ForeignKey(nameof(StudentId))]
        [InverseProperty("TeamAssignments")]
        public virtual Student Student { get; set; }
    }
}